server:
  port: ${CUSTOM.SERVER.PORT:8888}

encrypt:
  key: mitocode-secrets

spring:
  data:
    mongodb:
      database: mitocode
      host: 127.0.0.1
      port: 27017
      username: 'mitocode'
      password: 'mitocode'
      authentication-database: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:  
      enabled: true
    refresh:
      enable: true

config:
  oauth2:
    clientId: mitocode
    clientSecret: mitocode
    accesstoken_validity: 1
    refreshtoken_validity: 30
    privateKey: -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEAsBpHvLrkz6e3AfD4nQeCqC6BlBZf98A3aaw5Dju1N4FGVNSy
      eli1ypoTTC8C9TePCsBLL0XZH8MPq226MRf1exDnT1syY80RFivhqNAsmAk5ICdf
      OxLRHDGOCvGNcGvpNnUMR2EEgQvCqfXE7pOQDNm1vHIdqmtBgPAtyt7E/03rPj6d
      tGERMrtdlivexlIX+x6hIycJgQGgmEAnBHRgRTVOC0iLzKq7F/OGcwWrSe2Jf3gO
      11E187v37gaAt/2wdr22uf+SsjjLYnUNGpu85NkL3eEgUwJEsyPkXzFSG42+QP3e
      R7cW40FGI3qyS5BLO8UPg/OxOg5ykezsapj0lwIDAQABAoIBAC2nQn28/eCPnDQW
      on0jG046cEFR46M446Szjz8PX5V6IB+R3Is3QDm749DWRzAHLUAeRd+Ffhpr2T4Z
      /jEIAw3affzmqZOR8CINUj0PauAnU/Xv/xIzeJ6Ugjx4DrDcaONDSOGgVyiVQewJ
      2Pn4q1mJf0HRW7t4fszMdzKmue9td6vAet7s//5XDFFFnvkHxZ/XSvBHfM+cWRlA
      kB89UnzAk5thdWTM+9LdDZhxnGQe0XwvxXmURb+rezGIrfV+6POSobF6m7kwiW0x
      z+ynxCQ0i0PAlyM7F2mC38HpTw+Kxo2bmrnWjpd0AakTSqTA8+/RGgLZXLviLPAL
      M5s8ypECgYEA3BvLmlwLZE9cvzmavdWfXi+IQt7vzOTK+uA6twk/7hOKg1QvFaEz
      u6FyNFKpoulqWVcw6Efc+8xTFJqIvE+mZ6stukG2dW5IPBjA658oVpPfOSth0N6K
      pL5lnYlSH8MLQdusHZCuXvfbdLLadzxvBOEbP40PtHsID1d9KMYrWx0CgYEAzNGA
      3a9Oq4rBg1NJQIrcCBAKh0HMa6pE67q1WNccbqrD46NI0p8HPxxyjCy6Gk/E46Dk
      EhP+Qd6ViR2cc+Ia2y9/ZIaQsqZEejoyBP9MNjDH7UWuP3Ssvmnvd/lyF4rmBYk9
      A76UJflH96Ki4whyLYqIZRMyd1FwZDgsoL0pzEMCgYEAi5xxw2H4s9KG8J/4H8r8
      ///EPS4tClhgy0oo0+phC4CHjg96ogySxMN9reR0xumo1Cwy0FKsv2X1mI8Ahfk7
      gmwYYBjIQ6oE1WGaFJnqOygmIZv7ukE9zYsa5xav6YeMf2R3wnT/tSsfnuDHI3RI
      st6ZqvCtcnvLO/fxYkh4PZ0CgYBIwi/GEI2g0KTXsxF1lR5+2rvyuoQUxyK+ns/n
      JFtcUNtPlWS8NXQMjl1+wDDIQggOWMxMQ7/xxFFYqSU34V1q+Z+GpWrnm7r9tIiq
      T8rSAVg0SKmSry7iYZ2JABrwlA4Mb2k2WFAmgTx4ktTMU+bDmM/FICGwU0TaxT3N
      SAV+IwKBgQCtcD7kDDswoG2i+imV0K9pR1sZhPtK9kAjtNT32WhaH8YtRbXptlBR
      rgpSBdgSZAR2evlDv37vwyR28R45Daek0HmeUFjk4GZPcW6im87EAIbx9ERh+yp5
      RZ+9s5m9Ycj7eewRZXM7Kp2CiuIJt6UMxnc4d6Ya8TcoDqCSA1nIlw==
      -----END RSA PRIVATE KEY-----
    publicKey: -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsBpHvLrkz6e3AfD4nQeC
      qC6BlBZf98A3aaw5Dju1N4FGVNSyeli1ypoTTC8C9TePCsBLL0XZH8MPq226MRf1
      exDnT1syY80RFivhqNAsmAk5ICdfOxLRHDGOCvGNcGvpNnUMR2EEgQvCqfXE7pOQ
      DNm1vHIdqmtBgPAtyt7E/03rPj6dtGERMrtdlivexlIX+x6hIycJgQGgmEAnBHRg
      RTVOC0iLzKq7F/OGcwWrSe2Jf3gO11E187v37gaAt/2wdr22uf+SsjjLYnUNGpu8
      5NkL3eEgUwJEsyPkXzFSG42+QP3eR7cW40FGI3qyS5BLO8UPg/OxOg5ykezsapj0
      lwIDAQAB
      -----END PUBLIC KEY-----

### Actuator info (/actuator/info)
info:
  app:
    app-name: OAuth Server
    description: Microservicio para la autenticación de los usuarios
    version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  info:
    env:
      enabled: true