server:
  port: ${CUSTOM.SERVER.PORT:3333}

### Eureka Client configuration
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: ${EUREKA.HOST.SERVER:http://localhost:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    refresh:
      enable: true

### Actuator info (/actuator/info)
info:
  app:
    name: Product Query Service Microservice
    description: Microservicio para la consulta de los productos
    version: 1.0

### Mongo database configuration
spring:
  data:
    mongodb:
      host: localhost
      database: mitocode
      uri: mongodb://mitocode:mitocode@localhost:27018
      authentication-database: admin
  #webflux:
  #  base-path: '/product-service/v1'

kafka:
  mitocode:
    topic: mitocode
    server: 127.0.0.1
    port: 9092

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  info:
    env:
      enabled: true

#OpenAPI Configuration

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
